### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by PASSENGER128** [Bala93/KD-MRI#8]
when I read you code. i find that your dataset is h5 format. i want to know how can i get the dataset in h5 format.(my raw data is npy format)

**Comment by Bala93** [comment]
It is advisable to have the data in h5 format. Because, with npy, the entire data will be going to ram to get access to single slice, whereas in h5, it won't happen. Regarding, preparing h5 files, you can use the h5py modules. The writing process is very similar to writing in a text file, except that you have to give a key. Please check this https://www.christopherlovell.co.uk/blog/2016/04/27/h5py-intro.html
